version: '3.9'
services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: 'elios_redis'
    ports:
      - '6379:6379'
      - '8350:8001'
    networks:
      - powens_network
    volumes:
      - powens_volume:/data

  postgres:
    image: 'postgres'
    ports:
      - '5444:5432'
    container_name: 'elios_backend'
    environment:
      - POSTGRES_USER=elios_db
      - POSTGRES_DB=elios
      - POSTGRES_PASSWORD=eliosbackendpassword


  mailpit:
    image: 'axllent/mailpit'
    container_name: 'elios_mailpit'
    ports:
      - '1026:1025'
      - '8026:8025'
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - MP_MAX_MESSAGE=1000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_SSL_CERT=""
      - MP_SMTP_SSL_KEY=""
    networks:
      - powens_network
    volumes:
      - mailpit_data:/data


networks:
  powens_network:
    driver: bridge

volumes:
  powens_volume:
  mailpit_data:
