version: '3.8'
services:
  thorv2-redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8350:8001'
    networks:
      - powens_network
    volumes:
      - powens_volume:/data

networks:
  powens_network:
    driver: bridge

volumes:
  powens_volume:
